### PR TITLE
Specify Hyperparamter ranges for Embedding

### PR DESCRIPTION
**Pull request by djokester**
Fixes a part of #1420 
I have implemented choices only for dropout. 
Can someone review this?
I will implement changes for the rest of the hyperparameters for embedding post review.

### CODE REVIEW

**Comment by djokester** [comment]
@googlebot I signed it!

**Comment by haifeng-jin** [comment]
@djokester Thanks for the PR! I see you mark it as [WIP]. Is it ready for review now?

**Review by haifeng-jin — COMMENTED** [review]
So far looks good. If you would like to do all the hps in Embedding block, you can push more commits to this pull request. I will do another round of review when you finished.

**Comment by haifeng-jin** [comment]
@djokester The error is caused by a bug, which I just fixed in #1534.
This was a flaw in our design for this user-defined hp mechanism.
It has never been exposed by previous changes.
The Embedding block is a little special, which exposed the flaw.

You can rebase the master. The tests should pass then.

**Comment by djokester** [comment]
@haifeng-jin removed the WIP tag. Feel free to merge.

**Pull request merged**
