### PR TITLE
embedding block choice

### PR DESCRIPTION
**Pull request by mandalbiswadip**
Supposed to solve a part of #1420 

Providing hyperparameter ranges for Embedding Block.

1. When `pretraining` is 'none', the layer is supposed to load pretrained weights. I am not sure if it would be ideal to have a tunable 'embedding_dim' as it should be inferred from the pretrained models. I have included 'embedding_dim' as a tunable hyperparameter in this case as there is no pretrained model integrated as of now.

2. The `tests/integration_tests/io_api_test.py::test_io_api` is failing. Particularly the `Transformer` block in `TextBlock` is failing.
 
Failing case: The `embedding_dim` in the `Transformer` block is `32`, but when the 'Embedding' block is getting called inside the `Transformer` block, the `hp['text_block_1/transformer_1/embedding_2/embedding_dim'] = 128` value is overriding the `embedding_dim` inside the `build` function. This is resulting in an incompatibility in dimensions inside the 'Transformer' block.
I am not sure what the source of the value `hp['text_block_1/transformer_1/embedding_2/embedding_dim']` is.

### CODE REVIEW

**Comment by mandalbiswadip** [comment]
@haifeng-jin  please have a look at this.

**Comment by haifeng-jin** [comment]
@mandalbiswadip Thanks for the PR!
Would you rebase the latest master branch and try again?
It seems there are some conflicts.

**Comment by mandalbiswadip** [comment]
@haifeng-jin  it worked after rebasing. I guess this feature is already handled in #1525

**Comment by haifeng-jin** [comment]
@mandalbiswadip Yes. However, the fixes in the Transformer block are useful. I will take care of it to merge those lines.

**Pull request merged**
