### PR TITLE
Move docs generation into a separate repository.

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
### Which issue(s) does this Pull Request fix?
No issue in particular, it's linked to https://github.com/keras-team/keras/pull/13387 though.

### Details of the Pull Request

I'm trying to group the documentation generation into a single repository, which will be used in the multiple Keras projects in keras-team. The repository is currently https://github.com/gabrieldemarmiesse/keras-autodoc but we would move it later on in the keras-team organization.

### CODE REVIEW

**Comment by jhfjhfj1** [comment]
This is awesome! Thank you @gabrieldemarmiesse

**Comment by gabrieldemarmiesse** [comment]
This PR is ready to be merged but let's discuss it at the meeting Friday with @fchollet to make sure it's what he wants.

**Comment by jhfjhfj1** [comment]
@gabrieldemarmiesse Can we have a tag on the keras-autodoc for the pip install in CI? Since AutoKeras is automatically pushing the updates to master branch to the website, if the keras-autodoc master branch crashes, AutoKeras website would crash.

**Comment by gabrieldemarmiesse** [comment]
True. Let me pin the current version.

**Comment by gabrieldemarmiesse** [comment]
I pinned the version. 

I believe that after the 1.0, we should only publish the docs when we release a new version of autokeras on pypi, otherwise users are going to get confused. 

Most of them will have Autokeras installed from pip and they'll look at a documentation describing the new features of the master branch.

**Pull request merged**
