### PR TITLE
Updated ConvBlock dropout hyperparamter to have a range

### PR DESCRIPTION
**Pull request by kutal10**
Partial resolve for #1420 - chose to assist in ConvBlock - ready to be reviewed

### CODE REVIEW

**Review by haifeng-jin — CHANGES_REQUESTED** [review]
Thanks for the PR!
Please fix the following erros shown in the CI tests.
```
./autokeras/blocks/basic.py:265:86: E501 line too long (89 > 85 characters)
./autokeras/blocks/basic.py:266:86: E501 line too long (88 > 85 characters)
```

**Comment by kutal10** [comment]
> Thanks for the PR! Please fix the following erros shown in the CI tests.
> 
> ```
> ./autokeras/blocks/basic.py:265:86: E501 line too long (89 > 85 characters)
> ./autokeras/blocks/basic.py:266:86: E501 line too long (88 > 85 characters)
> ```

@haifeng-jin No problem - just fixed the docstring length in the two specified lines in commit [f59cbdd] above

**Comment by haifeng-jin** [comment]
@kutal10 
There are still some errors:
```
./autokeras/blocks/basic.py:266:42: W291 trailing whitespace
./autokeras/blocks/basic.py:267:57: W291 trailing whitespace
./autokeras/blocks/basic.py:311:10: E703 statement ends with a semicolon
```

You can use `sh shell/lint.sh` to run locally to check for the linting errors.
Thanks

**Comment by kutal10** [comment]
@haifeng-jin Corrected and reran linter with no errors as per commit 23f6e4f

**Review by haifeng-jin — APPROVED** [review]

**Pull request merged**
