### PR TITLE
[WIP] Use tf.data and tf.image for image augmentation

### LINKED ISSUE #669: Use tf.data and tf.image for image augmentation

### PR DESCRIPTION
**Pull request by Davidsirui**
A simple and scratchy try.

### Which issue(s) does this Pull Request fix?
resolves #669

### CODE REVIEW

**Comment by Davidsirui** [comment]
This is just a demo. Dr. Jin can have a look at it to see if the thought or direction is right. If it is OK to do so, I will complete this commit. If it is a wrong direction, we can discuss an alternative solution to it.

**Comment by jhfjhfj1** [comment]
@Davidsirui I will look into it and get back to you soon. Please remember to change the assignee to me whenever it is pending on me, even when it is not a review request. Thanks.

**Comment by Davidsirui** [comment]
No problem.I will have a try!


 
---Original---

**Comment by Davidsirui** [comment]
Dr. Jin I have completed all the test. And I don't delete the ImageTuner class. Because the other class calls it. Now you can have a look at the whole function(augment_iamge) to decide where we can use it.

**Comment by jhfjhfj1** [comment]
There are major changes in the master branch. Please change the pull request accordingly. If too many conflicts, you can close the pull request, start a new branch from master, copy and paste your code to it, and submit a new one. Thanks.

**Pull request closed without merging**
