### PR TITLE
Switch Docker example in to haifengjin/autokeras

### PR DESCRIPTION
**Pull request by chaselee**
This pull request updates the documentation for Docker. The previously referenced image is out of date. This image is only 18 days old and should be a more official source.

### CODE REVIEW

**Comment by chaselee** [comment]
May need to tweak some commands - only swapped the image reference thus far.

**Comment by cakemountain** [comment]
Also worth noting that documentation on the `docker run` command needs to be updated as well. In the new version the volumes are mounted differently. Whereas this worked with the previous image:

```
docker run -it -v "$(pwd)":/app --shm-size 2G garawalid/autokeras:latest python main.py
```

The new docker image...

```
docker run -it -v "$(pwd)":/app --shm-size 2G haifengjin/autokeras:latest python main.py
```

Fails:

```
python: can't open file './main.py': [Errno 2] No such file or directory
```

**Review by haifeng-jin — APPROVED** [review]
Thanks for the PR! LGTM

**Comment by haifeng-jin** [comment]
@cakemountain Thank you! I have created an issue. #1422

**Pull request merged**
