### PR TITLE
Remove tensorflow as dependency

### LINKED ISSUE #846: installation issue o
**My environment is a Jetson Xavier** 
Jetpack 4.2 
Ubuntu 18.04
python version is 3.6.8
relevant pip.list
dask (2.8.0)
dask-glm (0.2.0)
dask-ml (1.1.1)
Keras (2.3.1)
Keras-Applications (1.0.8)
Keras-Preprocessing (1.1.0)
numba (0.46.0)
numpy (1.17.4)
packaging (19.2)
pandas (0.25.3)
pandas-flavor (0.2.0)
pip (19.3.1)
scikit-learn (0.21.3)
scikit-MDR (0.4.4)
scipy (1.3.2)
tensorboard (1.14.0)
tensorflow-estimator (1.14.0)
**tensorflow-gpu (1.14.0+nv19.10)**

**error messages**
pip install git+git://github.com/keras-team/autokeras@master#egg=autokeras
Collecting autokeras
Cloning git://github.com/keras-team/autokeras (to revision master) to /tmp/pip-install-du3y560o/autokeras
Running command git clone -q git://github.com/keras-team/autokeras /tmp/pip-install-du3y560o/autokeras
ERROR: Could not find a version that satisfies the requirement tensorflow (from autokeras) (from versions: none)
ERROR: No matching distribution found for tensorflow (from autokeras)
**Then I tried**
pip install autokeras
Collecting autokeras
  Downloading https://files.pythonhosted.org/packages/c2/32/de74bf6afd09925980340355a05aa6a19e7378ed91dac09e76a487bd136d/autokeras-0.4.0.tar.gz (67kB)
     |████████████████████████████████| 71kB 3.8MB/s 
Collecting scipy==1.2.0
  Downloading https://files.pythonhosted.org/packages/ea/c8/c296904f2c852c5c129962e6ca4ba467116b08cd5b54b7180b2e77fe06b2/scipy-1.2.0.tar.gz (23.3MB)
     |████████████████████████████████| 23.3MB 12.6MB/s 
ERROR: Could not find a version that satisfies the requirement tensorflow==1.13.1 (from autokeras) (from versions: none)
**ERROR: No matching distribution found for tensorflow==1.13.1 (from autokeras)**

I have tried downgrading to tensorflow-gpu==1.13.1, but get the same error message
ERROR: No matching distribution found for tensorflow==1.13.1 (from autokeras)

My hunch is autokeras does not include tensorflow-gpu, thoughts on how to fix this?

thanks in advance for your assistance

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
### Which issue(s) does this Pull Request fix?

resolves #846

### Details of the Pull Request

Tensorflow comes now into two packages: tensorflow and tensorflow-cpu. By including either one or the other in the setup.py's requirements, we force the install on the user's machine. 

Since we don't know which one the user wants, we should refuse to install any. To prevent the use of outdated tensorflow packages, we can add a check when users use autokeras for the first time. 

This is similar to https://github.com/keras-team/keras-tuner/pull/177 but with an additional check at import time for the tensorflow version.

### CODE REVIEW

**Comment by jhfjhfj1** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/jhfjhfj1/autokeras/pullRequest?prid=4708694&bid=15728396)

**Comment by omalleyt12** [comment]
@gabrieldemarmiesse Would you be willing to add a similar change / error message for keras-tuner? I just released a minor kerastuner version (1.0.1) w/o this dependency but haven't updated GH yet, and a check like this would be nice

**Comment by gabrieldemarmiesse** [comment]
Sure thing. It's easy enough. I'll do it tonight/tomorrow.

**Comment by omalleyt12** [comment]
Great, thanks! No rush

**Pull request merged**
