### PR TITLE
Fix for typed API - Phase 2

### LINKED ISSUE #918: Adding types information on the API surface.
Adding types on the public API surface would allow us to do some runtime type checking later on and would allow user's IDE to have more info for static analysis. 

The functions/signatures to type are the ones listed here https://github.com/keras-team/autokeras/blob/master/autokeras/__init__.py

For the context, see #856 where I add some type information on a ImageClassifier.

This issue can be considered easy to solve (good first issue), it's just long to do because the public API surface is big.

I'll do it but some help is welcome :) make sure to make small pull requests.

### PR DESCRIPTION
**Pull request by dineshkumarsarangapani**
### Which issue(s) does this Pull Request fix?

resolves #918

### Details of the Pull Request

Added type hint for few more APIs and removed from the test

### CODE REVIEW

**Comment by haifeng-jin** [comment]
@dineshkumarsarangapani Is this PR ready for review? Thanks

**Comment by dineshkumarsarangapani** [comment]
> @dineshkumarsarangapani Is this PR ready for review? Thanks

@haifeng-jin yes it is ready for review.Thanks.

**Comment by dineshkumarsarangapani** [comment]
@haifeng-jin I just noticed that this PR is not marked for ready for review. I just did it.

**Review by haifeng-jin — APPROVED** [review]
Thanks for the PR! LGTM

**Pull request merged**
