### PR TITLE
[MRG] N-scalar output for ImageRegressor Class

### PR DESCRIPTION
**Pull request by BDANG**
This pull request resolves #ISSUE_NUMBER.

The details of the pull request:
ImageRegressor was modified to support N output nodes. I found that ImageRegressor's output shape (examples, 1) to be too restrictive.

The modified class supports output shapes of (examples, N). For example, you could train models to crop images; the output would be (examples, 4) where the 4 scalars represent the top, right, bottom, left crop distances.

### CODE REVIEW

**Comment by jhfjhfj1** [comment]
@BDANG Thank you very much for your contribution!
I have 2 questions for this PR.
1. Is it possible to make this class the same class as ImageRegressor, but make the regressor adaptively choose the "N" (may equal to 1 or not) according to the input data?
2. Would you refer us to any open dataset that has such kind of "N Regression" requirements?

**Comment by BDANG** [comment]
@jhfjhfj1 

1) It's entirely possible to modify ImageRegressor, yeah.

2) Unfortunately, I'm not aware of an open datasets that apply N-regression. But if we take [NVIDIA's research on modelling steering angle](https://arxiv.org/pdf/1604.07316v1.pdf), You could forecast maybe multiple steering angles (immediate steering angle and future steering angle).

If you want me to proceed with modifying ImageRegressor, I'm happy to do so!

**Comment by jhfjhfj1** [comment]
@BDANG Since we don't have any available open datasets on the NRegressor, I have concerns about the users need on this task.
So it would be great if you can just make the current Regressor capable of such multi-column regression by setting the default parameter instead of creating a new class.
In this way, we can support this functionality and add no extra maintenance burden to the project.
Thank you!

**Comment by BDANG** [comment]
@jhfjhfj1 ready for review!

**Pull request merged**
